package codeChallenges;

public class CodeChallenge1 {

  /*
 * This function takes a nucleotide text and checks it for patterns
 */
	public static int PatternCount(String text, String pattern) {
		int count = 0;
		
		for (int i = 0; i < (text.length() - pattern.length() + 1) ; i++) {
			
			if (text.substring(i, pattern.length() + i).equalsIgnoreCase(pattern)) {
				count++;
			}
		}
		return count;
	}
	
  // Main Method
	public static void main(String[] args) {
		
		System.out.println(PatternCount("ATTCACAATTCACAATTCACAATTCACAAAATTCACAGATATTCACACAAATCCCAATTCACATAACGATTCACAGGATTCACAGATTCACAATTCACAAACTATTCACAGTGTGCTATTCACAACTATCACGGCTCACGCTCCTTAATCAATTCACAATTCACACGATCCGATTCACAACCGTGCACATTCACAGTAAATTCACACATTCACAACTATTCACAATTCACAAATTCACAATTCACATCTGTATTCACACGCCCTGTAATTCACACACTCCATTCACAGATTCACAGTATTCACAATTCACACATCTATTCACATATTCACATCTGATTCACAATTCACAATTCACAATTCACAAATTCACAATTCACAGCTTCAGGATATTCACAATTCACATGGATTCACACCGATTCACAACATTCACATTATATTCACAATTCACACAATTCACAATTCACATATTCACACATTCACAGAATTCACAATTCACAATTCACAGATTCACAATTCACATCATTCACACATTCACAAGCAGTAAATTCACATAACGATCATTCACACATTCACAGAAGATTCACAATTCACAGTTCAATTCACACTTTATTCACAGATTCACAATTCACAAATTCACACCTAATTCACAATTCACACATTCACATAATTCACAAATCCCCAATTCACATTTATTCACATTATAATTCACACATTCACATCATTCACACGCATAAATTCACAGATTCACACTACCACTGGATTCACATATGATTCACAGATTCACACCATTCACAAATTCACACGACAATTTTCTATTCACATTATTCACAGATTCACACGTATTCACAGCATTCACAATTCACAATTCACATCTGATTCACAATTCACAATTCACAATTCACAGCGGTTATTCACAATTCACACCTCATTCACAAACGTGATTCACA", "ATTCACAAT"));
		

	}

}
